apiVersion: v1
kind: Secret
metadata:
  name: appointment
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTc=
  NAME: YW1uYQ==
  PASSWORD: MTIzNDU2
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config
data:
  MONGO_DB_NAME: "healthcare_database"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: amnasalahudin/appointments-service:30
        ports:
        - containerPort: 7070
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: appointment
              key: mongo-uri
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: appointment-config
              key: MONGO_DB_NAME
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: appointment
              key: NAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: appointment
              key: PASSWORD
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 15
          failureThreshold: 2
          periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
